server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          gogle:
            clientId: oauth Id
            clientSecret: oauth pw
            scope: profile,email
  profiles:
    include: oauth
  datasource:
    url: jdbc:h2:mem:Oauth
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

